### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor when verifying POST additions to .json file

### ISSUE THREAD

**Issue by hmamawal** [hmamawal/cy350_milestone_d_public#2]
when i try to verify the POST request by making a GET request to the new resource, i get the below error (see block terminal text).

https://github.com/hmamawal/cy350_milestone_d_public/blob/c3b60e654507cd56b1bfd5926aa8952280e433af/network_app.py#L94

```shell
cadet@CY350-VM:~/Documents/cy350/milestone_D$ sudo python3 network_app3.py 
The routers have been created!
The web server is running!
Routers are ready.
The web client is ready to send the request.
Enter 'GET' or 'POST' to test the respective request: post
Testing POST request...
POST Response:
Failed to connect to the server.
Verifying POST by GET request to the new resource...
Traceback (most recent call last):
  File "/home/cadet/Documents/cy350/milestone_D/network_app3.py", line 174, in <module>
    app.run_app()
  File "/home/cadet/Documents/cy350/milestone_D/network_app3.py", line 94, in run_app
    self.web_client.request_resource('/new_resource.html')
  File "/home/cadet/Documents/cy350/milestone_D/tcp_client.py", line 259, in request_resource
    connection = self.initiate_handshake()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cadet/Documents/cy350/milestone_D/tcp_client.py", line 71, in initiate_handshake
    self.client_socket.sendto(syn_datagram.to_bytes(), (self.gateway, 0))
OSError: [Errno 9] Bad file descriptor
```

**Comment by hmamawal** [comment]
https://github.com/hmamawal/cy350_milestone_d_public/blob/e85eff41be2dbb9a90e01791a0567be51a90e288/tcp_server.py#L251

I added this but it didn't help with file descriptor error
